post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVrYWkiLCJpZCI6IjVkYzk3NmU3MzRiYWI1MDg5MjA5M2RiNSIsImlhdCI6MTU3MzQ5MjYyMH0.hL9UPOqYMlGmDOYBTOS-zi1tXtYwIOH98fYM1lxZqQE

{
    "title": "Documentation",
    "author": "TailwindCSS",
    "url": "https://tailwindcss.com/",
    "likes": 6
}